#pragma once
#include <modules/component/component_type.h>
#include <modules/traits/modman_component_interface.h>

synapse_modules_export
synapse_modules_component_interface_handle
synapse_modules_component_manager_register_interface
	(synapse_modules_component_manager, synapse_modules_component_interface, const char*, void*);

synapse_modules_export
void
synapse_modules_component_manager_unregister_interface
	(synapse_modules_component_manager, synapse_modules_component_interface_handle);

synapse_modules_export
void
synapse_modules_component_manager_register_component
	(synapse_modules_component_manager, synapse_modules_component_handle);

synapse_modules_export
void
synapse_modules_component_manager_unregister_component
	(synapse_modules_component_manager, synapse_modules_component_handle);

synapse_modules_export
synapse_modules_component_interface_handle
synapse_modules_component_manager_retrieve_interface
	(synapse_modules_component_manager, const char*);